QUOTES = [
  { quote: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus" },
  { quote: "If the only tool you have is a hammer, you tend to see every problem as a nail.", author: "Abraham Maslow" },
  { quote: "You can teach a student a lesson for a day; but if you can teach him to learn by creating curiosity, he will continue the learning process as long as he lives.", author: "Clay P. Bedford" },
  { quote: "Aim for success, not perfection. Never give up your right to be wrong, because then you will lose the ability to learn new things and move forward with your life. Remember that fear always lurks behind perfectionism.", author: "David M. Burns" },
  { quote: "A teacher affects eternity; he can never tell where his influence stops.", author: "Henry B Adams" },
  { quote: "Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.", author: "Mark Twain" },
  { quote: "The first problem for all of us, men and women, is not to learn, but to unlearn.", author: "Gloria Steinem" },
  { quote: "Children have never been very good at listening to their elders, but they have never failed to imitate them.", author: "James Baldwin" },
  { quote: "Education is a progressive discovery of our own ignorance.", author: "Will Durant" },
  { quote: "The difference between school and life? In school, you're taught a lesson and then given a test. In life, you're given a test that teaches you a lesson.", author: "Tom Bodett" },
  { quote: "Tell me and I'll forget; show me and I may remember; involve me and I'll understand.", author: "Chinese proverb" },
  { quote: "If someone is going down the wrong road, he doesn't need motivation to speed him up. What he needs is education to turn him around.", author: "Jim Rohn" },
  { quote: "People learn something every day, and a lot of times it's that what they learned the day before was wrong.", author: "Bill Vaughan" },
  { quote: "Education cost money, but then so does ignorance.", author: "Claus Moser" },
  { quote: "What sculpture is to a block of marble education is to the human soul.", author: "Joseph Addison" },
  { quote: "Education makes a people easy to lead but difficult to drive: easy to govern, but impossible to enslave.", author: "Peter Brougham" },
  { quote: "Do not train children to learning by force and harshness, but direct them to it by what amuses their minds, so that you may be better able to discover with accuracy the peculiar bent of the genius of each.", author: "Plato" },
  { quote: "It is in fact a part of the function of education to help us escape, not from our own time — for we are bound by that — but from the intellectual and emotional limitations of our time.", author: "T.S. Eliot" },
  { quote: "If people did not do silly things, nothing intelligent would ever get done.", author: "Ludwig Wittgenstein" },
  { quote: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
  { quote: "Knowledge will give you power, but character respect.", author: "Bruce Lee" },
  { quote: "True love is not so much a matter of romance as it is a matter of anxious concern for the well-being of one's companion.", author: "Gordon B. Hinckley" },
  { quote: "The only disability in life is a bad attitude.", author: "Scott Hamilton" },
  { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { quote: "In the multitude of words there wanteth not sin: but he that refraineth his lips is wise.", author: "Proverbs 10:19" },
  { quote: "One who smiles rather than rages is always the stronger.", author: "Japanese Proverb" },
  { quote: "What is life? It is the flash of a firefly in the night. It is the breath of a buffalo in the wintertime. It is the little shadow which runs across the grass and loses itself in the sunset.", author: " Blackfoot Proverb" },
  { quote: "Everyone who is successful must have dreamed of something.", author: "Maricopa Proverb" },
  { quote: "Adversity is a good teacher.", author: "Russian Proverb" },
  { quote: "The first to apologize is the bravest. The first to forgive is the strongest. The first to forget is happiest.", author: "Unknown" },
  { quote: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "Bruce Lee" },
  { quote: "The aim of the wise is not to obtain pleasure, but to avoid pain.", author: "Aristotle" },
  { quote: "A wise man makes his own decisions, an ignorant man follows the public opinion.", author: "Grantland Rice" },
  { quote: "Let me embrace thee, sour diversity, for wisemen say it is the wisest course.", author: "William Shakespeare" },
  { quote: "Life's tragedy is that we get old too soon and wise too late.", author: "Benjamin Franklin" },
  { quote: "The art of being wise is the art of knowing what to overlook.", author: "William James" },
  { quote: "Where ignorance is bliss, 'Tis folly to be wise.", author: "Thomas Gray" },
  { quote: "If you persuade yourself that you can do a certain thing, provided this thing be possible, you will do it, however difficult it may be. If, on the contrary, you imagine that you cannot do the simplest thing in the world, it is impossible for you to do it, and molehills become for you unscalable mountains.", author: "Emile Coue" },
  { quote: "It is not wise to violate rules until you know how to observe them.", author: "T.S. Eliot" },
  { quote: "Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).", author: "Mark Twain" },
  { quote: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare" },
  { quote: "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.", author: "Isaac Asimov" },
  { quote: "Count your age by friends, not years. Count your life by smiles, not tears.", author: "John Lennon" },
  { quote: "Hold fast to dreams. For if dreams die. Life is a broken-winged bird. That cannot fly.", author: "Langston Hughes" },
  { quote: "Never laugh at live dragons.", author: "J.R.R. Tolkein" },
  { quote: "The Linux philosophy is 'Laugh in the face of danger'. Oops. Wrong One. 'Do it yourself'. Yes, that's it.", author: "Linus Torvalds" },
  { quote: "Intelligence is the ability to avoid doing work, yet getting the work done.", author: "Linus Torvalds" },
  { quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { quote: "The secret of life, though, is to fall seven times and to get up eight times.", author: "Paulo Coelho" },
  { quote: "Never let your sense of morals prevent you from doing what is right.", author: "Isaac Asimov" },
  { quote: "The simple things are also the most extraordinary things, and only the wise can see them.", author: "Paulo Coelho" },
  { quote: "There are three things all wise men fear: the sea in storm, a night with no moon, and the anger of a gentle man.", author: "Patrick Rothfuss" },
  { quote: "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", author: "Confucious" },
  { quote: "Angry people are not always wise.", author: "Jane Austen" },
  { quote: "Let no man pull you so low as to hate him.", author: "Martin Luther King, Jr." },
  { quote: "You do not write your life with words... You write it with actions. What you think is not important. It is only important what you do.", author: "Patrick Ness" },
  { quote: "Be more concerned with your character than your reputation, because your character is what you really are, while your reputation is merely what others think you are.", author: "John Wooden" },
  { quote: "A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them.", author: "John C. Maxwell" }
]

QUOTES.each do |quote|
  Quote.find_or_create_by(quote: quote[:quote], author: quote[:author])
end
